spring.application.name=backend
spring.profiles.active=local

spring.datasource.url=jdbc:mysql://localhost:3306/medvault
spring.datasource.username=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true